version: '3.8'

services:
  # Основное приложение FastAPI
  app:
    build: .
    container_name: tender_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/tenders
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  # База данных PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: tender_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tenders
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Кеш и брокер сообщений Redis
  redis:
    image: redis:7-alpine
    container_name: tender_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# Сохраняем данные даже после остановки контейнеров
volumes:
  postgres_data:
  redis_data: